apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: api-configmap
  namespace: k8stest
data:
  application.properties: |
    spring.datasource.url=jdbc:postgresql://k8stest-postgresql.k8stest.svc.cluster.local/k8stest
    spring.datasource.username=k8stest
    spring.datasource.password=k8stest
    spring.datasource.hikari.maximumPoolSize=4

    spring.kafka.bootstrap-servers=k8stest-kafka-controller-0.k8stest-kafka-controller-headless.k8stest.svc.cluster.local:9092,k8stest-kafka-controller-1.k8stest-kafka-controller-headless.k8stest.svc.cluster.local:9092,k8stest-kafka-controller-2.k8stest-kafka-controller-headless.k8stest.svc.cluster.local:9092
    spring.kafka.security.protocol=SASL_PLAINTEXT
    spring.kafka.properties.sasl.mechanism=SCRAM-SHA-256
    spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
    username="k8stest" \
    password="k8stest";

    spring.data.redis.host=k8stest-redis-master.k8stest.svc.cluster.local
    spring.data.redis.password=k8stest