apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: k8stest-api
  name: k8stest-api
  namespace: k8stest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8stest-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8stest-api
        monitored: foobar
    spec:
      containers:
      - image: k8stest-api:0.1.11
        imagePullPolicy: Never
#      for microk8s cluster described in homelablog.md
#      - image: 192.168.1.101:32000/k8stest-api:0.1.11
        name: k8stest-api
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 9090
        volumeMounts:
          - name: config-volume
            mountPath: /workspace/config
        ports:
          - containerPort: 9090
            name: metrics
            protocol: TCP
      volumes:
        - name: config-volume
          configMap:
            name: api-configmap
status: {}
