apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: k8stest-api
  name: k8stest-api
  namespace: k8stest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8stest-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8stest-api
    spec:
      containers:
      - image: k8stest-api:0.1.10
        imagePullPolicy: Never
        name: k8stest-api
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 2Gi
status: {}
