apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: k8stest-listener
  name: k8stest-listener
  namespace: k8stest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8stest-listener
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8stest-listener
    spec:
      containers:
      - image: k8stest-listener:0.1.10
        imagePullPolicy: Never
        name: k8stest-listener
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 2Gi
        volumeMounts:
          - name: config-volume
            mountPath: /workspace/config
      volumes:
        - name: config-volume
          configMap:
            name: listener-configmap
status: {}
