prometheus:
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
  service:
    type: LoadBalancer
grafana:
  service:
    type: LoadBalancer
  sidecar:
    dashboards:
      enabled: true
