apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: k8stest-service
  name: k8stest-service
  namespace: k8stest
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: k8stest-service
status:
  loadBalancer: {}
