apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: k8stest
  name: k8stest
  namespace: k8stest
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    app: k8stest
  type: NodePort
status:
  loadBalancer: {}
